### ISSUE TITLE
ruby scripts empty response when amonagent starts as service

### ISSUE THREAD

**Issue by djsakisd** [amonapp/amonagent#21]
Ruby scripts dont run with amonagent service..  They only run if i call amonagent manually from command line.

I changed the startup script line 20 to `DAEMON='/usr/bin/amonagent -debug`
and also line 34 to ` STDOUT=/var/log/amonagent/amonagent.log
` in order to log all the output to log fine and heres the output  :

 ` "checks": [
  {
   "name": "",
   "command": "check-dir-size.rb  -d /var/log/",
   "exit_code": 0,
   "output": "",
   "error": "exec: not started"
  },
  {
   "name": "",
   "command": "check-qmailq.rb",
   "exit_code": 0,
   "output": "",
   "error": "exec: not started"
  }
 ]`

Also some more info : 
`# su -s /bin/bash amonagent
bash-4.1$ env
HOSTNAME=xxx.xxx.com
rvm_bin_path=/usr/local/rvm/bin
GEM_HOME=/usr/local/rvm/gems/ruby-2.4.0
SHELL=/bin/bash
MY_RUBY_HOME=/usr/local/rvm/rubies/ruby-2.4.0
SSH_TTY=/dev/pts/2
USER=amonagent
rvm_path=/usr/local/rvm
rvm_prefix=/usr/local
PATH=/usr/local/rvm/gems/ruby-2.4.0/bin:/usr/local/rvm/gems/ruby-2.4.0@global/bin:/usr/local/rvm/rubies/ruby-2.4.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin
MAIL=/var/spool/mail/root
_=/bin/env
PWD=/usr/local/rvm/gems/ruby-2.4.0/bin
LANG=C
_system_arch=x86_64
GEM_PATH=/usr/local/rvm/gems/ruby-2.4.0:/usr/local/rvm/gems/ruby-2.4.0@global
LESSOPEN=||/usr/bin/lesspipe.sh %s
RUBY_VERSION=ruby-2.4.0
`

and some more info : 
` gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.4.0 (2016-12-24 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.4.0
  - USER INSTALLATION DIRECTORY: /etc/opt/amonagent/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.4.0/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.4.0/bin
  - SPEC CACHE DIRECTORY: /etc/opt/amonagent/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-2.4.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.4.0
     - /usr/local/rvm/gems/ruby-2.4.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.4.0/bin
     - /usr/local/rvm/gems/ruby-2.4.0@global/bin
     - /usr/local/rvm/rubies/ruby-2.4.0/bin
     - /usr/lib64/qt-3.3/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/local/rvm/bin
     - /root/bin
`

If i run manually #amonagent all ruby checks runs fine.
Tried to run the bin with supervisord but still no success..
 Tried to put the full path of the rb file in checks.conf still no success.
Tried to put "ruby path" "rb file path" still nothing.. 

If i run amonagent -test-plugin=checks all report fine no errors there.. See output : 
`$ whoami
amonagent
bash-4.1$ amonagent -test-plugin=checks
[{"name":"","command":"check-dir-size.rb  -d /var/log/","exit_code":2,"output":"CheckDirSize CRITICAL: Directory /var/log/ is greater than 4,000,000 bytes [actual size: 28,671,141 bytes]\n","error":""} {"name":"","command":"check-qmailq.rb","exit_code":0,"output":"CheckQMAILQ OK: 0 messages in the remote queue\n","error":""}]

Executed in 91.506987ms`

Tried also the example in docs and the output is also empty : 

` "plugins": {
  "nginx": {
   "gauges": {
    "connections.active": 52,
    "connections.reading": 0,
    "connections.waiting": 48,
    "connections.writing": 1,
    "connections_total.accepts": 2261,
    "connections_total.handled": 2261,
    "requests_per_second": 2
   }
  },
  "sensu": {}
 },
 "checks": [
  {
`
but if i run /opt/amonagent/amonagent -test-plugin=sensu : `  "sensu": {
   "sensu.xxxxxx.com": {
    "gauges": {
     "gr_iostat.avg-cpu_pct_idle": "83.67",
     "gr_iostat.avg-cpu_pct_iowait": "0",
     "gr_iostat.avg-cpu_pct_nice": "0",
     "gr_iostat.avg-cpu_pct_steal": "0",
     "gr_iostat.avg-cpu_pct_system": "3.52",
     "gr_iostat.avg-cpu_pct_user": "12.81",
     "gr_iostat.loop0_avgqu-sz": "0",
     "gr_iostat.loop0_avgrq-sz": "8",
`

OS : Centos x64 6.9
tried both ruby 2.3 installed with rvm & also installed with rpm repo : https://www.softwarecollections.org/en/scls/rhscl/rh-ruby23/

on ubuntu x64 16.04 it runs fine..

Any idea on what the problem might be ?

**Comment by martinrusev** [comment]
@djsakisd The problem might be because `amonagent` as a service is run by the `amonagent` user, which may not have access to the ruby scripts. To solve the problem, I usually provide the full path: `/path/to/sensu/check-qmailq.rb`

**Comment by djsakisd** [comment]
Hi @martinrusev sorry forgot to write it but this was the first thing that come to my mind as well but unfortunately it didn't work. Tried also various combinations on the command but had no luck either .
I really can't understand why if I run manually it works but as a service it won't.

Tried to change the user insise service script to bee root also tried to run  manually the agent through cron  with @reboot and as a last resort put the bin fine in rc.local but nothing seems to work either .

Even tried with supervisor.

Most probably it's a centos thing rather an issue with agent since sensu scripts works fine on Ubuntu 16 .

Anyway thanks for replying me.

If anything else to try comes to mind please let me know .

I will close the issue as it's system specific.
