### ISSUE TITLE
Amazon Linux dependency issue for RPM

### ISSUE THREAD

**Issue by perplext** [amonapp/amonagent#22]
Error: Package: 1:amonagent-0.7.5.2-1.x86_64 (amon)
           Requires: adduser
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by Grisu118** [comment]
Same problem on my centos 7 machine, any ideas?

**Comment by Grisu118** [comment]
Installing the rpm manually with --nodeps solved the problem for me
adduser is present on centos but not as package.

**Comment by martinrusev** [comment]
@Grisu118, @perplext  can you try again, I pushed a fix to the repositories

**Comment by Grisu118** [comment]
yes, it is fixed. Thanks
